data_path: /home/shared/veas/denit_pilot_b_250214.csv
taglist: /home/shared/veas/Tagliste_denit_prosesshaller.xlsx
skiprows_taglist: 2
sheets: [0, 1]
cluster_sets: true

t_len: 20                 # Sequence length

targets:
- Nitratmåling ut, kolonne B i pilot

inputs:
- Nitrat, dentank, PH1
- Oksygen, dentank, PH1
- Ammonium, NIT, PH1
- Orto-P, dentank, PH2
- Trykk under filterbunn, kolonne B i pilot
- Trykk over filterbunn, kolonne B i pilot
- Temperatur utløp
- Metanoldosering, kolonne B i pilot
- Vannstrømning til kolonne B i pilot
- Vannstrømning, innløp

time_variable: Time

random_state: 42
data_savepath: processed_data/veas/data_pilot_clustered.npz
metadata_dir: processed_data/veas/data_pilot_clustered_meta

clustering:
  eps: 1.0
  min_samples: 10

hydra:
  run:
    dir: ./${now:%Y-%m-%d}/${now:%H-%M-%S}