data:
  path: /processed_data/vessel_power/data_canonical_split.npz

training:
  device: cuda
  loss_fn: mse            # Loss function. Options: mse, mae, huber, tukey, quantile
  huber_delta: 1.0          # Huber loss parameter delta
  tukey_c: 4.685            # Tukey loss parameter c
  quantile_quantile: 0.5    # Quantile loss parameter

  nr_epochs: 5000           # Number of epochs
  lr: 1e-4                 # Learning rate
  optimizer: adam           # Optimizer. Options: sgd, adam, adamw, rmsprop, adagrad, adabielief
  batch_size: 1024            # Batch size
  weight_decay: 1e-4         # Weight decay

  log_freq: 10              # Logging frequency
  cp_freq: 500              # Checkpoint frequency

  use_sam: true
  sam_rho: 0.05

model:
  fc_hidden_sizes: [64, 32, 64]     # List of hidden layer sizes for fully connected layers 
  lstm_hidden_size: 100           # Number of hidden units in the LSTM
  dropout: 0.0              # Dropout rate
  activation: tanh          # Activation function. Options: relu, elu, leaky_relu, tanh, sigmoid

regularization:
  l1_reg: 0.0               # L1 regularization parameter
  l2_reg: 0.0               # L2 regularization parameter

scaling:
  scaler: standard          # Scaler. Options: standard, minmax, robust, quantile

hydra:
  run:
    dir: ./models/${now:%Y-%m-%d}/${now:%H-%M-%S}