data_path: "../data/veas/data_preprocessed.npz"
model_path: "./models/2025-02-17/20-21-59"
batch_size: null
loss_fn: "mse"
device: "cpu"
cp_list: [100,500,1000,2000,3000,4000,5000]
clamp_output_nonnegative: true

loss_parameters:
  loss_fn_list: [mse, mae, huber, tukey, quantile]
  huber_delta: 1.0          # Huber loss parameter delta
  tukey_c: 4.685            # Tukey loss parameter c
  quantile_quantile: 0.5    # Quantile loss parameter


hydra:
  run:
    dir: ${model_path}/test
